# Generated by Django 4.2.1 on 2023-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='images/')),
                ('urls_path', models.URLField()),
            ],
        ),
    ]
